display_name: Songloft客户端
msix_version: 1.0.0.0
store: "true"
logo_path: web/icons/Icon-512.png
languages: zh-cn, en-us

# Microsoft Store 发布必需配置
# 以下字段需要与 Microsoft Store 仪表板中注册的信息匹配
publisher: CN=C6C6ACD3-DAF2-47DB-B6A8-800945835CEF
publisher_display_name: 涵曦
identity_name: BA26D70F.Songloft
