display_name: Songloft
package_name: songloft
maintainer:
  name: Songloft Team
  email: dev@songloft.org
priority: optional
section: sound
installed_size: 102400
icon: assets/icons/app_icon.png
keywords:
  - Music
  - Player
  - Self-hosted
generic_name: Music Player
categories:
  - Audio
  - Music
  - Player
startup_notify: true
